### ISSUE TITLE
Incorrect shield on the barracks.

### ISSUE THREAD

**Issue by StanleySweet** [0ADMods/terra_magna#10]
According to Wolflance:
> I don't recall seeing this type of pentagonal shield in use during Han Dynasty either (most are gourd-shaped). I hope someone could prove me wrong though, because I kinda like the design.

This should be changed

![rbytls9](https://user-images.githubusercontent.com/6837402/40140765-010627b2-5954-11e8-862a-c75c9ceb22af.png)

**Comment by StanleySweet** [comment]
@AlexanderVzla  Should be a trivial fix :)

**Comment by AlexanderVzla** [comment]
![image](https://user-images.githubusercontent.com/29136612/40945926-d383d5f8-6828-11e8-8e5a-2ff74caf1b47.png)
Fixed
