### ISSUE TITLE
Use a historically correct bixie

### ISSUE THREAD

**Issue by StanleySweet** [0ADMods/terra_magna#27]
Concerned buildings, glory statue in delenda est, gov center, civ center
![image](https://user-images.githubusercontent.com/6837402/40143904-10594592-595d-11e8-8cc3-9e104a437972.png)

![image](https://user-images.githubusercontent.com/6837402/40143884-fd2cddc6-595c-11e8-90ee-7011af780113.png)

High poly version [statue_bixie-00.zip](https://github.com/0ADMods/terra_magna/files/7728981/statue_bixie-00.zip)

(CC-BY-SA 3.0 Unported)

**Comment by StanleySweet** [comment]
@AlexanderVzla Might be a good tutorial :)

**Comment by lastrodamo** [comment]
I create a base mesh.
![0ad_han_bixie-01](https://user-images.githubusercontent.com/10653143/133149968-73b533ad-62a6-418e-9455-f1c631ba4ec8.png)

Now I will sculpt it and bake textures ...

**Comment by StanleySweet** [comment]
https://github.com/0ADMods/han_china/issues/53

**Comment by lastrodamo** [comment]
I finalise the Bixie statue low poly with 1053 tris and albedo texture.
[https://3dminfographie.com/images/graphisme-3d/0ad/0ad_han_bixie-02.png](url)
