### ISSUE TITLE
Add champions

### ISSUE THREAD

**Issue by StanleySweet** [0ADMods/terra_magna#31]
Wolflance said:
> Since there is none yet, may I suggest:

> - Cavalry Lancer (Yu Lin Guard)
> - Horse Archer (Bow) (Hu Ben Guard)
> - Two-handed Swordsman Infantry
> - Hybrid Melee-Crossbow Infantry - May be hard to implement, judging from the discussion about dual-role unit like Theurophoroi.

**Comment by AlexanderVzla** [comment]
Cavalry lancer should be updated ?

**Comment by StanleySweet** [comment]
@AlexanderVzla Indeed
