### ISSUE TITLE
Trireme could use a rudder

### ISSUE THREAD

**Issue by StanleySweet** [0ADMods/terra_magna#34]
![image](https://user-images.githubusercontent.com/6837402/40144371-a33f76be-595e-11e8-9a48-a007d58ffa7d.png)

**Comment by StanleySweet** [comment]
I belive you worked on the ship, could you add the rudder please ?

**Comment by AlexanderVzla** [comment]
Ah trireme, i've though it was the tower ship: fixed
![image](https://user-images.githubusercontent.com/29136612/40945339-648b547a-6826-11e8-82f4-8b77cb02a591.png)
