### ISSUE TITLE
xiongnu: no disappearing rubble

### ISSUE THREAD

**Issue by udeved** [0ADMods/terra_magna#40]
The xiongnu building rubble does not disapear over time.
The fire prop keeps smoking.
It disappears, if the save game is loaded.

**Comment by StanleySweet** [comment]
@AlexanderVzla maybe because of the construction hack you made ?

**Comment by AlexanderVzla** [comment]
they share the same behavior of the kart faction but only some structures remain whitout dissapear, houses work well any idea why?
