### ISSUE TITLE
Include Thebans from Delenda est 

### ISSUE THREAD

**Issue by tomasmatys** [0ADMods/terra_magna#50]
https://wildfiregames.com/forum/index.php?/topic/24726-terra-magna-terra-magna-is-now-available/&page=2

**Comment by wltonlopes** [comment]
Is this still expected? If yes I can help, we have a virtually ready civ in no Delenda Est mod.

**Comment by tomasmatys** [comment]
Well yes but Thebans should be updated first in their own https://github.com/0ADMods/theban_greeks which then we can make requirements as seen here https://github.com/0ADMods/terra_magna/commit/2c6ec7b535d6ae4b9c514243a54bf0a9c84ff26e  and bundled upon the release, I need to figure it out how.

**Comment by wltonlopes** [comment]
I have a thread from thebans github, just missing some art files with errors.

**Comment by StanleySweet** [comment]
Closed by d13528856adb0cc648c4dee29ea26e5c3e0527cc
