### ISSUE TITLE
Han - Rice Field Missing

### ISSUE THREAD

**Issue by Jeeppler** [0ADMods/terra_magna#56]
The Han had a rice field previous to the integration into Terra Magna. As of Alpha 23 the rice field does not exist anymore. The Han have now the normal wheat fields.

**Comment by niektb** [comment]
That's not a bug but a team decision :) We didn't manage to get good looking rice field that also looks nice on terrain slopes :)

**Comment by Jeeppler** [comment]
Hmm, sad I really liked the rice fields.
