### ISSUE TITLE
Zapotecs - No champion units

### ISSUE THREAD

**Issue by Jeeppler** [0ADMods/terra_magna#59]
The Zapotecs have no champion units. Civilizations without champion units are harder to play. It would be nice to have champion units implemented for the Zapotecs.

**Comment by wltonlopes** [comment]
I think it would be interesting to pay a little attention to the Zapotecs (and the Xiongnu) before a new launch for Alpha 24. We could add a noble champion lancer as a combatant champion, and a generic king for Zapotecs and Xiongnu we have names their historical kings.
