### ISSUE TITLE
Zapotecs - Conquering Xiongnu Blacksmith Allows to Train Wagons

### ISSUE THREAD

**Issue by Jeeppler** [0ADMods/terra_magna#60]
While playing the Zapotecs against Xiongnu, I (Zapotecs) conquered a Xiongnu blacksimth. The blacksmith allowed me to train wagons. So, I trained one even though I played as Zapotec. I was able to drive the wagon around and unpack it. It then became a store yurt (tent). However, I was unable to pack the yurt again, because I did not have a nomadic skill. 

The correct behavior should be, that I am unable to train wagons and only see my own tech upgrades in a conquered blacksmith.

**Comment by tomasmatys** [comment]
I try to look into it.

**Comment by StanleySweet** [comment]
Fixed in https://github.com/0ADMods/terra_magna/commit/05ebd17d7dda85d53fdfeb06abeb6c912355113e
