### ISSUE TITLE
han-field

### ISSUE THREAD

**Issue by liulitchi** [0ADMods/terra_magna#63]
in this file  ~/simulation/templates/structures/chin_field.xml,
there's a bug in line 5 as follows:
 <SpecificName>?</SpecificName>.
I suggest change this ? to Tián(田)，it means 田地 in modern chinese,  ie farm field

**Comment by StanleySweet** [comment]
Yes thank you :) Feel free to submit a patch of you can. You can make other
suggestions as well :)
