### ISSUE TITLE
 Zapotecs - Conquering Xiongnu Blacksmith Allows to Train Xiongnu Ram

### ISSUE THREAD

**Issue by Jeeppler** [0ADMods/terra_magna#65]
I played as Zapotecs against the Xiongnu. It is possible to train the Xiongnu ram in the blacksmith building after conquering the Xiongnu blacksmith. This should not be possible.

**Comment by StanleySweet** [comment]
fixed in https://github.com/0ADMods/terra_magna/commit/05ebd17d7dda85d53fdfeb06abeb6c912355113e
