### ISSUE TITLE
How do we keep Han and TM in sync?

### ISSUE THREAD

**Issue by udeved** [0ADMods/terra_magna#67]
@StanleySweet 

I made a little [testing branch](https://github.com/0ADMods/HanChina/tree/use-new) with the new buildings and added couple of techs.
Feel free to test and backport what you deem useful.

The question arises, how do we keep the two mods in sync?

In order to achieve that, I propose some simple points we follow.
For example, all xml have a default indent of 4 characters, no tabs. This should already reduce changes of mismatches.

**Comment by StanleySweet** [comment]
Game standard is two spaces for XML files.
I'll have a look at the branch if I have some time.

Keeping it in sync is I believe always gonna be tricky :/

**Comment by udeved** [comment]
Might be possible to add a git remote to TM and Han serving as upstream repo for Han specific changes.

**Comment by StanleySweet** [comment]
Yeah but git subrepo works fine when it's a subfolder, here it's not. It's mixed everywhere.
If you find a solution though let me know.

**Comment by udeved** [comment]
Sure,  subrepo would required TM to be reorganized, and encapsulate each civ as much as possible.
Alternatively, subrepo is folder based, but subrepo supports other nested subrepos, question would be more usuability with a n-depth level of subrepos.
But overall, subrepo would be the kind of thing that solved the sync problem best.

**Comment by StanleySweet** [comment]
You can't really reorganize it. It's like this because of the game.

**Comment by StanleySweet** [comment]
Let's remove the chinese faction totally from this mod, and add it as dependency instead.

**Comment by udeved** [comment]
I would also recommend to split out the xiongnu.
The Han military is heavily geared towards a nomadic cavalry enemy, perhaps Han should depend on Xiongnu?
TM would become more like a meta mod that pulls factions.

**Comment by StanleySweet** [comment]
> Split out the Xiongnu
Sure they can have their own mod. I dont't have the time to do that though.
> Han china depending on Xiongnu
I dont think that's a good idea. Han_china is supposed to be standalone not dependant else this whole enterprise makes no sense
> TM meta mod
Yeah I agree. The goal is mod like de do the same.
