### ISSUE TITLE
Xiongnu hero's name

### ISSUE THREAD

**Issue by liulitchi** [0ADMods/terra_magna#68]
File Path:  https://github.com/0ADMods/terra_magna/blob/master/simulation/data/civs/xion.json 

In line 99 , there's a string for Xiongnu hero "Màodùn", but 冒顿 pronounce 
"Mòdú" in  ancient chinese .

**Comment by StanleySweet** [comment]
Can you make a pull request ? :)

**Comment by liulitchi** [comment]
ok

**Comment by tomasmatys** [comment]
Thank you for your find, keep them coming.
